services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - main
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    command: sh -c "python3 manage.py migrate && python3 manage.py collectstatic --noinput && gunicorn v_movies.wsgi -b 0.0.0.0:8000"
    container_name: app
    volumes:
      - .:/code/
      - ./staticfiles:/code/staticfiles
      - ./media:/code/media
    depends_on:
      - postgres
    expose:
      - "8000"
    networks:
      - main
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    command: nginx -g "daemon off;"
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/staticfiles
      - ./media:/code/media
    depends_on:
      - app
      - postgres
    networks:
      - main
    restart: always

volumes:
  postgres_data:

networks:
  main: