# Generated by Django 5.1 on 2024-11-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_otpcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="زمان پایان اشتراک"
            ),
        ),
    ]
