# Generated by Django 5.1 on 2024-11-14 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_subscription_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="has_supscription",
        ),
    ]
