# Generated by Django 5.1 on 2025-01-31 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_user_has_supscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subscription_time",
        ),
    ]
