# Generated by Django 5.1 on 2025-02-06 09:03

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_user_subscription_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpcode",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[accounts.validators.validate_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[accounts.validators.validate_phone_number],
                verbose_name="شماره موبایل",
            ),
        ),
    ]
