# Generated by Django 5.1 on 2025-02-07 08:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price_per_month", models.PositiveIntegerField()),
                ("credits_per_month", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "پلن",
                "verbose_name_plural": "پلن ها",
                "ordering": ["price_per_month"],
            },
        ),
        migrations.CreateModel(
            name="Subscriptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription_start_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("subscription_end_timestamp", models.DateTimeField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="subscription.plan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "اشتراک",
                "verbose_name_plural": "اشتراک ها",
                "ordering": ("subscription_start_timestamp",),
            },
        ),
    ]
