# Generated by Django 5.1 on 2024-08-25 18:53

import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='اسم بازیگر')),
                ('last_name', models.CharField(max_length=60, verbose_name='فامیلی بازیگر')),
                ('slug', models.SlugField(allow_unicode=True, max_length=300, unique=True)),
                ('position', models.IntegerField()),
            ],
            options={
                'verbose_name': 'بازیگر',
                'verbose_name_plural': 'بازیگران',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='نام فارسی')),
                ('english_name', models.CharField(max_length=350, verbose_name='نام انگلیسی')),
                ('year_of_manufacture', models.IntegerField(verbose_name='سال ساخت')),
                ('slug', models.SlugField(allow_unicode=True, max_length=300, unique=True)),
                ('made_in', models.CharField(choices=[('ایالات متحده آمریکا', 'ایالات متحده آمریکا'), ('ایران', 'ایران'), ('کانادا', 'کانادا'), ('انگلستان', 'انگلستان'), ('آلمان', 'آلمان'), ('فرانسه', 'فرانسه'), ('ایتالیا', 'ایتالیا'), ('روسیه', 'روسیه'), ('چین', 'چین'), ('ژاپن', 'ژاپن'), ('هند', 'هند'), ('برزیل', 'برزیل'), ('استرالیا', 'استرالیا'), ('مکزیک', 'مکزیک'), ('آفریقای جنوبی', 'آفریقای جنوبی'), ('ترکیه', 'ترکیه'), ('عربستان سعودی', 'عربستان سعودی'), ('آرژانتین', 'آرژانتین'), ('مصر', 'مصر'), ('اسپانیا', 'اسپانیا'), ('لهستان', 'لهستان'), ('هلند', 'هلند')], max_length=30, verbose_name='کشور سازنده')),
                ('legal_age', models.PositiveIntegerField(verbose_name='سن قانونی')),
                ('film_time', models.PositiveIntegerField(null=True, verbose_name='زمان ویدیو')),
                ('score', models.FloatField(max_length=3, verbose_name='امتیاز')),
                ('story', models.CharField(max_length=500, verbose_name='داستان فیلم')),
                ('about_movie', models.CharField(max_length=500, verbose_name='درباره فیلم')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='تصویر')),
                ('trailer', models.FileField(blank=True, null=True, upload_to='video', verbose_name='تریلر فیلم')),
                ('videofile', models.FileField(blank=True, null=True, upload_to='video', verbose_name='ویدیو ی فیلم')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('actors', models.ManyToManyField(to='movies.actor', verbose_name='بازیگران')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'فیلم',
                'verbose_name_plural': 'فیلم ها',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movies.film')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_on'],
            },
        ),
    ]
