# Generated by Django 5.1 on 2024-09-19 18:35

import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60, verbose_name='اسم کامل بازیگر')),
                ('slug', models.SlugField(allow_unicode=True, max_length=300, unique=True)),
                ('position', models.IntegerField()),
            ],
            options={
                'verbose_name': 'بازیگر',
                'verbose_name_plural': 'بازیگران',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='اسم ژانر')),
                ('slug', models.CharField(max_length=60)),
                ('position', models.IntegerField()),
            ],
            options={
                'verbose_name': 'ژانر',
                'verbose_name_plural': 'ژانر ها',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='نام فارسی')),
                ('english_title', models.CharField(max_length=350, verbose_name='نام انگلیسی')),
                ('year_of_manufacture', models.IntegerField(verbose_name='سال ساخت')),
                ('slug', models.SlugField(allow_unicode=True, max_length=300, unique=True)),
                ('country', models.CharField(choices=[('ایالات متحده آمریکا', 'ایالات متحده آمریکا'), ('ایران', 'ایران'), ('کانادا', 'کانادا'), ('انگلستان', 'انگلستان'), ('آلمان', 'آلمان'), ('فرانسه', 'فرانسه'), ('ایتالیا', 'ایتالیا'), ('روسیه', 'روسیه'), ('چین', 'چین'), ('ژاپن', 'ژاپن'), ('هند', 'هند'), ('برزیل', 'برزیل'), ('استرالیا', 'استرالیا'), ('مکزیک', 'مکزیک'), ('آفریقای جنوبی', 'آفریقای جنوبی'), ('ترکیه', 'ترکیه'), ('عربستان سعودی', 'عربستان سعودی'), ('آرژانتین', 'آرژانتین'), ('مصر', 'مصر'), ('اسپانیا', 'اسپانیا'), ('لهستان', 'لهستان'), ('هلند', 'هلند')], max_length=30, verbose_name='کشور سازنده')),
                ('legal_age', models.PositiveIntegerField(verbose_name='سن قانونی')),
                ('score', models.FloatField(max_length=3, verbose_name='امتیاز از ده')),
                ('story', models.CharField(max_length=500, verbose_name='داستان فیلم')),
                ('about_movie', models.CharField(max_length=500, verbose_name='درباره فیلم')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='تصویر')),
                ('trailer', models.FileField(blank=True, null=True, upload_to='video', verbose_name='تریلر فیلم')),
                ('is_perimium', models.BooleanField(default=False)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('duraction', models.PositiveIntegerField(null=True, verbose_name='زمان ویدیو به دقیقه')),
                ('videofile', models.FileField(blank=True, null=True, upload_to='video', verbose_name='ویدیو ی فیلم')),
                ('download_link_480', models.CharField(max_length=80, null=True, verbose_name='لینک دانلود با کیفیت 480')),
                ('download_link_720', models.CharField(max_length=80, null=True, verbose_name='لینک دانلود با کیفیت 720')),
                ('download_link_1080', models.CharField(max_length=80, null=True, verbose_name='لینک دانلود با کیفیت 1080')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('actors', models.ManyToManyField(to='movies.actor', verbose_name='بازیگران')),
                ('genres', models.ManyToManyField(to='movies.genre', verbose_name='ژانر ها')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'فیلم',
                'verbose_name_plural': 'فیلم ها',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='MovieComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movies.movie')),
            ],
            options={
                'verbose_name': 'نظر فیلم سینمایی ها',
                'verbose_name_plural': 'نظرات فیلم سینمایی ها',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='نام فارسی')),
                ('english_title', models.CharField(max_length=350, verbose_name='نام انگلیسی')),
                ('year_of_manufacture', models.IntegerField(verbose_name='سال ساخت')),
                ('slug', models.SlugField(allow_unicode=True, max_length=300, unique=True)),
                ('country', models.CharField(choices=[('ایالات متحده آمریکا', 'ایالات متحده آمریکا'), ('ایران', 'ایران'), ('کانادا', 'کانادا'), ('انگلستان', 'انگلستان'), ('آلمان', 'آلمان'), ('فرانسه', 'فرانسه'), ('ایتالیا', 'ایتالیا'), ('روسیه', 'روسیه'), ('چین', 'چین'), ('ژاپن', 'ژاپن'), ('هند', 'هند'), ('برزیل', 'برزیل'), ('استرالیا', 'استرالیا'), ('مکزیک', 'مکزیک'), ('آفریقای جنوبی', 'آفریقای جنوبی'), ('ترکیه', 'ترکیه'), ('عربستان سعودی', 'عربستان سعودی'), ('آرژانتین', 'آرژانتین'), ('مصر', 'مصر'), ('اسپانیا', 'اسپانیا'), ('لهستان', 'لهستان'), ('هلند', 'هلند')], max_length=30, verbose_name='کشور سازنده')),
                ('legal_age', models.PositiveIntegerField(verbose_name='سن قانونی')),
                ('score', models.FloatField(max_length=3, verbose_name='امتیاز از ده')),
                ('story', models.CharField(max_length=500, verbose_name='داستان فیلم')),
                ('about_movie', models.CharField(max_length=500, verbose_name='درباره فیلم')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='تصویر')),
                ('trailer', models.FileField(blank=True, null=True, upload_to='video', verbose_name='تریلر فیلم')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('episodes_number', models.PositiveIntegerField(default=0)),
                ('seasons', models.PositiveIntegerField(default=1, verbose_name='فصل ها')),
                ('is_perimium', models.BooleanField(default=False)),
                ('actors', models.ManyToManyField(to='movies.actor', verbose_name='بازیگران')),
                ('genres', models.ManyToManyField(to='movies.genre', verbose_name='ژانر ها')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'سریال',
                'verbose_name_plural': 'سریال ها',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='SerialComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movies.serial')),
            ],
            options={
                'verbose_name': 'نظر سریال ها',
                'verbose_name_plural': 'نظرات سریال ها',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='SerialEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان قسمت')),
                ('number_of_episode', models.IntegerField(verbose_name='قسمت چندم')),
                ('videofile', models.FileField(blank=True, null=True, upload_to='video', verbose_name='ویدیو ی این قسمت')),
                ('download_link_480', models.CharField(max_length=80, verbose_name='لینک دانلود با کیفیت 480')),
                ('download_link_720', models.CharField(max_length=80, verbose_name='لینک دانلود با کیفیت 720')),
                ('download_link_1080', models.CharField(max_length=80, verbose_name='لینک دانلود با کیفیت 1080')),
                ('season', models.PositiveIntegerField(verbose_name='فصل')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='episodes', to='movies.serial')),
            ],
            options={
                'verbose_name': 'قسمت سریال',
                'verbose_name_plural': 'قسمت های سریال',
                'ordering': ['number_of_episode'],
            },
        ),
    ]
