# Generated by Django 5.1 on 2024-08-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_time',
            field=models.PositiveIntegerField(null=True, verbose_name='زمان ویدیو به دقیقه'),
        ),
        migrations.AlterField(
            model_name='film',
            name='score',
            field=models.FloatField(max_length=3, verbose_name='امتیاز از ده'),
        ),
    ]
