# Generated by Django 5.1 on 2025-03-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="score",
            field=models.FloatField(max_length=3, verbose_name="امتیاز از پنج"),
        ),
        migrations.AlterField(
            model_name="serie",
            name="score",
            field=models.FloatField(max_length=3, verbose_name="امتیاز از پنج"),
        ),
    ]
