# Generated by Django 5.1 on 2024-08-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_film_film_time_alter_film_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
    ]
