# Generated by Django 5.1 on 2024-08-26 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_genre_film_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='movie',
        ),
    ]
