# Generated by Django 5.1 on 2024-08-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_film_actors_remove_film_genres_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviecomments',
            options={'ordering': ['-created_on'], 'verbose_name': 'نظر فیلم سینمایی ها', 'verbose_name_plural': 'نظرات فیلم سینمایی ها'},
        ),
        migrations.AlterModelOptions(
            name='serialcomments',
            options={'ordering': ['-created_on'], 'verbose_name': 'نظر سریال ها', 'verbose_name_plural': 'نظرات سریال ها'},
        ),
    ]
